# Generated by Django 3.2.6 on 2021-08-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_facebooj_url_userprofile_facebook_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='facebook_url',
            new_name='github_url',
        ),
    ]
